# ansible-playbook -i inv/all -i inv/lan -l raspberry playbook/raspberry/leds.yml
---
- name: shutdown leds
  hosts: all

  tasks:
  - name: shutdown leds
    shell: echo 0 | sudo tee /sys/class/leds/led1/brightness > /dev/null && echo 0 | sudo tee /sys/class/leds/led0/brightness