---
- name: change password test
  hosts: all
  tasks:
  - name: Change 'test' password
    user: name=test password="$y$j9T$APFjpnbahgFbzFyn6Lk5d.$5N/2bg42oD4oPTo3aIPuu6iYyt64hZsW3RmDUQQ2830" update_password=always
