# ansible-playbook -i inv/all -i inv/iptables -l <machine> playbook/util/upgrade.yml
---
- name: debian update and upgrade
  hosts: all
  tasks:
  - name: update
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: upgrade
    apt: upgrade=dist force_apt_get=yes