---
- name: debug
  hosts: all
  gather_facts: False
  ignore_unreachable: yes
  tasks:
    - name: check connectivity
      ping:
      register: connectivity
    - name: print test
      debug: var=connectivity
    - name: print error
      debug: var=connectivity['msg']
      when: connectivity['unreachable'] is defined
