# ansible-playbook -i inv/all -i inv/lan -l <machine> playbook/debug/vars.yml
---
- name: debug
  hosts: all
  tasks:

  - name: print
    debug: var=test

  - name: print when
    debug: var=machine
    when: machine == 'master'

  - name: print when
    debug: var=machine
    when: machine is defined
