---
- name: remove apache
  hosts: all
  tasks:
    - name: remove apache
      apt: name={{ item }} state=absent
      loop:
        - apache2
        - php
        - php-mysql
        - php-xml
        - php-zip
        - php-mbstring
        - php-gd
        - php-curl
        - php-intl
        - php-imagick
        - php-bcmath
        - php-gmp
        - php-apcu
        - libapache2-mod-php