---
- hosts: kubernetes node config
  tasks:
    - name: initialize the cluster
      shell: kubeadm init
    - name: create .kube directory
      become_user: {{ user_node }}
      file: path=$HOME/.kube state=directory mode=0755
    - name: copy admin.conf to user's kube config
      copy: src=/etc/kubernetes/admin.conf dest=/home/vicfd/.kube/config remote_src=yes owner=vicfd
    - name: install Pod network
      become_user: {{ user_node }}
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml