---
- name: mariadb config
  hosts: all
  tasks:
    - name: install mysql dependency
      apt: name=python3-mysqldb state=latest
    - name: create databases
      mysql_db: name={{ databases }} state=present
    - name: configure admin
      mysql_user: name={{ admin_name }} host={{ admin_host }} password={{ admin_password }} encrypted=yes priv={{ admin_permission }} state=present