# ansible-playbook -i inv/all -i inv/lan -l <machine> playbook/install/apache-php.yml
---
- import_playbook: ../util/upgrade.yml
- name: debian apache and php installer
  hosts: all
  tasks:
    - name: install packages
      apt: name={{ item }} state=latest
      loop:
        - apache2
        - php
        - php-mysql
        - php-xml
        - php-zip
        - php-mbstring
        - php-gd
        - php-curl
        - php-intl
        - php-imagick
        - php-bcmath
        - php-gmp
        - php-apcu
        - libapache2-mod-php