---
- import_playbook: ../util/upgrade.yml
- name: install apache
  hosts: all
  tasks:
    - apt: name={{ item }} state=latest
      loop:
        - apache2
        - php
        - php-mysql
        - php-xml
        - php-zip
        - php-mbstring
        - php-gd
        - php-curl
        - php-intl
        - php-imagick
        - php-bcmath
        - php-gmp
        - php-apcu
        - libapache2-mod-php