---
- import_playbook: ../util/upgrade.yml
- name: install docker
  hosts: all
  tasks:
    - name: install docker
      apt: name={{ item }} state=latest
      loop:
        - docker
        - docker-compose