---
- import_playbook: ../util/upgrade.yml
- name: install mariadb
  hosts: all
  tasks:
    - name: install mariadb
      apt: name=mariadb-server state=latest
    - name: bind 0.0.0.0
      ansible.builtin.lineinfile: path='/etc/mysql/mariadb.conf.d/50-server.cnf' regexp='^bind-address' line='bind-address=0.0.0.0'
      notify: restart mysql service
  handlers:
    - name: restart mysql service
      ansible.builtin.service: name=mysql state=restarted