# ansible-playbook -i inv/all -i inv/lan -l <machine> playbook/install/mariadb.yml
---
- import_playbook: ../util/upgrade.yml
- name: debian mariadb installer
  hosts: all
  tasks:
    - name: install mariadb
      apt: name=mariadb-server state=latest
    - name: bind 0.0.0.0
      ansible.builtin.lineinfile: path='/etc/mysql/mariadb.conf.d/50-server.cnf' regexp='^bind-address' line='bind-address=0.0.0.0'
      register: bind
    - name: restart service if modify conf
      ansible.builtin.service: name=mysql state=restarted
      when: bind.changed