---
- name: install rollup
  hosts: all
  tasks:
    - name: register proxy rollup
      shell: ls /usr/local/avamar/bin | grep 'avosrollup' | wc -l
      register: proxy_rollup
    - name: show proxy rollup
      debug: var=proxy_rollup.stdout
    - name: stop if installed
      meta: end_host
      when: proxy_rollup.stdout | int == 1
    - name: create remote directory to copy rpm
      file: path=/root/packages state=directory mode='0755'
    - name: copy required rpm
      copy: src=/home/vicfd/rollup/{{ item }} dest=/root/packages mode='0444'
      loop:
        - 'sec_install_os_errata_sles.pl'
        - 'sec_os_updates_SLES12SP5-2022-R1plus-v4.tgz'
    - name: install rollup
      shell: perl /root/packages/sec_install_os_errata_sles.pl /root/packages/sec_os_updates_SLES12SP5-2022-R1plus-v4.tgz
    - name: delete rpm
      file: path=/root/packages/{{ item }} state=absent
      loop:
        - 'sec_install_os_errata_sles.pl'
        - 'sec_os_updates_SLES12SP5-2022-R1plus-v4.tgz'
